# Generated by Django 4.0.3 on 2022-04-02 15:10

from django.db import migrations, models
import django_countries.fields
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Last Name')),
                ('check_in', models.DateField(max_length=150, verbose_name='Name')),
                ('check_out', models.DateField(max_length=150, verbose_name='Name')),
                ('number_of_guests', models.IntegerField(default=1, verbose_name='Number of guests')),
                ('billing_address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Billing Address')),
                ('billing_country', django_countries.fields.CountryField(max_length=2)),
                ('postal_code', models.IntegerField(default=1, verbose_name='Postal code')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='City')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=150, null=True, verbose_name='Phone Number')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
